name: Continuous Integration

on:
  push:
    branches:
      - master
      - fix-inline-sed
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test Installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Zsh
        if: runner.os == 'Linux'
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Test Installer
        run: ./setup.sh -t robbyrussell -p "docker git" -u yes